CREATE TABLE categories 
  ( 
     id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT, 
	 parent_id BIGINT(20) UNSIGNED DEFAULT NULL,
     name VARCHAR(255) NOT NULL, 
     image_path TEXT NULL, 
     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
     updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
     PRIMARY KEY (id),
	 FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE CASCADE ON UPDATE CASCADE
  )